### ISSUE TITLE
Jax Installation

### ISSUE THREAD

**Issue by Achleshwar** [Mumeishi514/d_2nerf#10]
Hi authors, thanks for releasing the code! I am currently facing issues while running this repo on GPU (it's working on CPU but it takes forever). I think the problem is with the required version of jax and cuda support. 

Can you please provide more details regarding the CUDA version and NVIDIA drivers that you are using for jax 0.2.26? TIA

**Comment by m-richa** [comment]
I am having the same problem.

**Comment by ChikaYan** [comment]
Hi, thank you for your interest in our work! Our environment should be exactly the same as HyperNeRF. For CUDA we used 11.3, and for Jax we used 0.2.27, but we are aware that this specific Jax version seems to have been removed from the Jax wheel. Did you encounter any issues when installing the environment?

**Comment by wangyuyy** [comment]
I had the same problem.
I installed the environment with following commands:
```shell
pip install -r requirements.txt
pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
But the error was reported after the second command.
```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.6.3 requires numpy~=1.19.2, but you have numpy 1.22.4 which is incompatible.
torch 2.0.1 requires nvidia-cublas-cu11==11.10.3.66; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu11 11.11.3.6 which is incompatible.
torch 2.0.1 requires nvidia-cuda-cupti-cu11==11.7.101; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu11 11.8.87 which is incompatible.
torch 2.0.1 requires nvidia-cuda-runtime-cu11==11.7.99; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu11 11.8.89 which is incompatible.
torch 2.0.1 requires nvidia-cudnn-cu11==8.5.0.96; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu11 8.9.2.26 which is incompatible.
```

**Comment by xjli360** [comment]
> Hi authors, thanks for releasing the code! I am currently facing issues while running this repo on GPU (it's working on CPU but it takes forever). I think the problem is with the required version of jax and cuda support.
> 
> Can you please provide more details regarding the CUDA version and NVIDIA drivers that you are using for jax 0.2.26? TIA

hi, i had solved the problem.here is my solution that may help you:
To keep the version with the same as hypernerf:
`pip install --upgrade jax==0.2.20 jaxlib==0.1.71+cuda111 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`
`pip install flax==0.3.6`

And be careful this command which can upgrade the jax and jaxlib:
`pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html`

By the way, you can execute the command to verify：
`python -c "import jax;print(jax.devices())"`
if work, it will print like this:
`[GpuDevice(id=0, process_index=0), GpuDevice(id=1, process_index=0), GpuDevice(id=2, process_index=0), GpuDevice(id=3, process_index=0)]
`
