### ISSUE TITLE
How can I get the same video file as the project page after training? I only have some runtime_eval png files. Thanks

### ISSUE THREAD

**Issue by HelloTaeyeon** [Mumeishi514/d_2nerf#14]

**Comment by ChikaYan** [comment]
Which video file are you referring to? The novel views of static scene, or the decoupled static/dynamic rendering?

**Comment by HelloTaeyeon** [comment]
> Which video file are you referring to? The novel views of static scene, or the decoupled static/dynamic rendering?



> Which video file are you referring to? The novel views of static scene, or the decoupled static/dynamic rendering?

I just ran  train_eval_balloon.sh

**Comment by ChikaYan** [comment]
If you uncomment the evaluation lines in the script, it would run `eval.py` which should produce the renderings that you are looking for
