### ISSUE TITLE
Colmap calibration.

### ISSUE THREAD

**Issue by FreemanG** [Mumeishi514/d_2nerf#19]
Thanks for sharing this work.

Your paper mentioned that "we do not apply any masks when registering real-world images using COLMAP".
I wonder if your estimated camera poses are good enough for reconstruction, especially when performing SfM on a dynamic scene.

**Comment by ChikaYan** [comment]
Hi, thanks for your interest in our work.

We follow HyperNeRF's preprocessing code to COLMAP. For all scenes that succeeded with COLMAP, we observed good quality with the estimated camera poses. Typically, if the dynamic object does not occlude too much of the view, and if it doesn't have too much texture, the quality of camera poses would be higher.

Hope that helps!
