### ISSUE TITLE
Generate novel views

### ISSUE THREAD

**Issue by YYYYYHC** [Mumeishi514/d_2nerf#3]
Hi, the project is cool but I may need some help with generating novel views. Where should I modify it?

**Comment by d2nerf** [comment]
Hi,

Our code is the same as HyperNeRF in terms of this. Novel views could be generated using [this notebook](https://colab.research.google.com/github/google/nerfies/blob/main/notebooks/Nerfies_Capture_Processing.ipynb) and saved as test cameras under `camera-paths/`. Then the evaluation script `eval.py` should be able to automatically read and render them as long as you set `EvalConfig.num_test_eval = -1`
