### ISSUE TITLE
Pillow model

### ISSUE THREAD

**Issue by logchan** [Mumeishi514/d_2nerf#6]
Hi,

Thanks for publishing your synthetic dataset and including the kubrics scripts and blender files.

I'd like to do some tunings of the dataset, and I was able to find all the models from shapenet, except for the pillow. May I ask where the pillow model is from and how do you configured it in kubrics?

Thanks

**Comment by ChikaYan** [comment]
Hi,

The pillow scene was not generated using Kubric as it only supports rigid objects. The pillow model is obtained from ShapeNet.

Best

**Comment by logchan** [comment]
Got it, thanks!
