### ISSUE TITLE
How to save rendering results as ply？

### ISSUE THREAD

**Issue by SakuBorder** [Mumeishi514/d_2nerf#9]
I want to save the rendered result as a ply file. Where should I modify it？

**Comment by ChikaYan** [comment]
Hi,

To my understanding, ply file is used to save geometry info such as mesh or point clouds. If that's what you meant, you could take the mean or median depths (they should already be computed and returned as an output), use ray origin and direction to obtain point location, and store all the points as a ply file. Hope that helps.

**Comment by SakuBorder** [comment]
Thankyou for your apply,but i still have some questions.I obtained the value of ‘depth’ and the value of 'rgb' from modelout, but after converting it to a point cloud, the rendering of the points is very sparse, and there is no color of rgb. However, the point cloud synthesized using a single frame depth map and regular is relatively dense and has color. How can I obtain a dense point cloud or mesh with color for all reconstruction results? Can it be done according to the method you mentioned?

**Comment by SakuBorder** [comment]
> Hi,
> 
> To my understanding, ply file is used to save geometry info such as mesh or point clouds. If that's what you meant, you could take the mean or median depths (they should already be computed and returned as an output), use ray origin and direction to obtain point location, and store all the points as a ply file. Hope that helps.

Thank you for your apply,but i still have some questions.I obtained the value of ‘depth’ and the value of 'rgb' from modelout, but after converting it to a point cloud, the rendering of the points is very sparse, and there is no color of rgb. However, the point cloud synthesized using a single frame depth map and regular is relatively dense and has color. How can I obtain a dense point cloud or mesh with color for all reconstruction results? Can it be done according to the method you mentioned?

**Comment by ChikaYan** [comment]
> However, the point cloud synthesized using a single frame depth map and regular is relatively dense and has color

What do you mean by synthesizing with a single frame depth map?

To obtain dense points, you may try rendering with multiple frames and concatenating the extracted points together. However, it is still an open problem how to obtain the correct RGB for those points.

**Comment by SakuBorder** [comment]
> > However, the point cloud synthesized using a single frame depth map and regular is relatively dense and has color
> 
> What do you mean by synthesizing with a single frame depth map?
> 
> To obtain dense points, you may try rendering with multiple frames and concatenating the extracted points together. However, it is still an open problem how to obtain the correct RGB for those points.

For single frame depth maps, I use the d2nerf model  generate the depth map and the corresponding rgb image for each frame, Depth maps+RGB images+intrinsics can be used to obtain the point cloud for this frame.And this frame of point cloud is colored. 

If I want to obtain point clouds or mesh with the correct color for all scenes displayed in the entire video, can I only obtain point clouds frame by frame and perform point cloud registration and stitching?I mean in the framework of d2nerf. 


And can we separate the depth of dynamic and static states？

**Comment by ChikaYan** [comment]
> For single frame depth maps, I use the d2nerf model generate the depth map and the corresponding rgb image for each frame, Depth maps+RGB images+intrinsics can be used to obtain the point cloud for this frame.And this frame of point cloud is colored.

That should be the best approach to extract the geometry. However, note that the RGB given by the ray does not necessarily correspond to the true color of the extracted point due to semi-transparency or blending effect.

> If I want to obtain point clouds or mesh with the correct color for all scenes displayed in the entire video, can I only obtain point clouds frame by frame and perform point cloud registration and stitching?I mean in the framework of d2nerf.

This is the best way and should give you point clouds with best quality. You can also obtain mesh by thresholding the density field via marching cubes, but this can be very noisy.

> And can we separate the depth of dynamic and static states？

Yes, if you modified the rendering function and return the depth/RGB separately.

**Comment by SakuBorder** [comment]
> > For single frame depth maps, I use the d2nerf model generate the depth map and the corresponding rgb image for each frame, Depth maps+RGB images+intrinsics can be used to obtain the point cloud for this frame.And this frame of point cloud is colored.
> 
> That should be the best approach to extract the geometry. However, note that the RGB given by the ray does not necessarily correspond to the true color of the extracted point due to semi-transparency or blending effect.
> 
> > If I want to obtain point clouds or mesh with the correct color for all scenes displayed in the entire video, can I only obtain point clouds frame by frame and perform point cloud registration and stitching?I mean in the framework of d2nerf.
> 
> This is the best way and should give you point clouds with best quality. You can also obtain mesh by thresholding the density field via marching cubes, but this can be very noisy.
> 
> > And can we separate the depth of dynamic and static states？
> 
> Yes, if you modified the rendering function and return the depth/RGB separately.

Thank you for your reply and hope to continue communicating with you！
